WIP
DataDog/java-profiler pull request #149
Opened 2024-11-04 18:05 UTC by jbachorik

**What does this PR do?**:

**Motivation**:

**Additional Notes**:

**How to test the change?**:

**For Datadog employees**:
- [ ] If this PR touches code that signs or publishes builds or packages, or handles
  credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.
- [ ] JIRA: [JIRA-XXXX]

Unsure? Have a question? Request a review!

2024-11-05 11:27 UTC, jbachorik commented on ddprof-lib/src/main/java/com/datadoghq/profiler/JVMAccess.java
> +        public boolean getBooleanFlag(String name) {
These are not getters

2024-11-06 14:28 UTC, MattAlp requested changes
Need to verify a few things with this PR and its interaction with dd-trace-java, will follow-up & approve if no troubles emerge.

2024-11-06 14:28 UTC, MattAlp commented on ddprof-lib/src/main/java/com/datadoghq/profiler/JVMAccess.java
> +     * Currently, only string and boolean flags can be modified. Allowing modification of numeric
I would specify as-of details here

2024-11-06 14:28 UTC, MattAlp commented on ddprof-lib/src/main/java/com/datadoghq/profiler/LibraryLoader.java
> +        public final boolean success;
Nit over some PR review confusion on line 166: could we use `succeeded` instead of `success` for the outcome var?

2024-11-06 14:28 UTC, MattAlp commented on ddprof-lib/src/main/java/com/datadoghq/profiler/JVMAccess.java
> +            System.out.println("[WARNING] Failed to obtain JVM access.\n" + result.error);
Could use logging here instead?

2024-11-06 14:28 UTC, MattAlp commented on ddprof-lib/src/main/java/com/datadoghq/profiler/JVMAccess.java
> +                System.out.println("[WARNING] Failed to obtain JVM access.\n" + result.error);
Same as above re: logging

2024-11-06 15:20 UTC, jbachorik commented on ddprof-lib/src/main/java/com/datadoghq/profiler/JVMAccess.java
> +            System.out.println("[WARNING] Failed to obtain JVM access.\n" + result.error);
No :(
Logging is not available. We are not pulling in any logging library

2024-11-07 13:50 UTC, MattAlp commented on ddprof-lib/src/main/java/com/datadoghq/profiler/JVMAccess.java
> +            System.out.println("[WARNING] Failed to obtain JVM access.\n" + result.error);
I was hoping for a shim to dd-trace if available, but that goes back to the coupling issue

2024-11-08 17:20 UTC, jbachorik commented on ddprof-lib/src/main/java/com/datadoghq/profiler/LibraryLoader.java
> +        public final boolean success;
Done

2024-11-08 17:20 UTC, jbachorik commented on ddprof-lib/src/main/java/com/datadoghq/profiler/JVMAccess.java
> +     * Currently, only string and boolean flags can be modified. Allowing modification of numeric
Sorry, I don't understand - what should I specify here?

2024-11-08 17:24 UTC, jbachorik commented
@MattAlp I have decoupled the library initialization from the profiler initialization. Now, when you don't use profiler only the most important parts will be initialized - basically just the JNI bindings, vmstructs and safeacees. Anything related to JVMTI, capabilities, hooks etc. is registered only when one asks for `JavaProfiler.instance()`

2024-11-12 13:12 UTC, MattAlp approved these changes

2024-11-12 15:23 UTC, merged